backend:
  name: git-gateway
  branch: main

media_folder: "images/poster"
public_folder: "/images/poster"

site_url: https://sparkly-jalebi-a2951b.netlify.app

collections:
  - name: "posters"
    label: "메인 포스터"
    folder: "images/poster"
    create: true
    delete: true
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "포스터 이미지", name: "image", widget: "image"}
